using BrassLedger.Application.Accounting;
using BrassLedger.Domain.Accounting;
using BrassLedger.Infrastructure.Auth;
using Microsoft.EntityFrameworkCore;

namespace BrassLedger.Infrastructure.Accounting;

public sealed partial class AccountingTransactionService
{
    public async Task<TransactionResult> AuthorizeSupplierReturnAsync(AuthorizeSupplierReturnRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PurchasingManage)) return TransactionResult.Failure("You are not authorized to approve supplier returns.");
        var requested = request.Lines?.Where(line => line.Quantity != 0m).ToArray() ?? [];
        if (string.IsNullOrWhiteSpace(request.ReturnNumber) || string.IsNullOrWhiteSpace(request.Reason) || requested.Length == 0 || requested.Any(line => line.InventoryReceiptLineId == Guid.Empty || RoundQuantity(line.Quantity) <= 0m) || requested.Select(line => line.InventoryReceiptLineId).Distinct().Count() != requested.Length)
            return TransactionResult.Failure("A return number, reason, and one positive quantity per selected receipt line are required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken);
        var companyId = await ResolveCompanyIdAsync(db, cancellationToken);
        var receipt = await db.InventoryReceipts.SingleOrDefaultAsync(item => item.Id == request.InventoryReceiptId && item.CompanyId == companyId, cancellationToken);
        if (receipt is null) return TransactionResult.Failure("Inventory receipt not found.");
        if (receipt.Status != "Posted") return TransactionResult.Failure("Only a posted inventory receipt can be returned.");
        if (!string.Equals(receipt.ConcurrencyToken, request.ReceiptConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The inventory receipt changed after it was opened. Refresh and review it again.");
        if (request.AuthorizedOn < receipt.ReceivedOn) return TransactionResult.Failure("The return authorization date cannot precede the receipt date.");
        var returnNumber = request.ReturnNumber.Trim();
        if (await db.SupplierReturnAuthorizations.AnyAsync(item => item.CompanyId == companyId && item.ReturnNumber == returnNumber, cancellationToken)) return TransactionResult.Failure("Supplier-return number already exists.");
        var receiptLines = await db.InventoryReceiptLines.Where(line => line.InventoryReceiptId == receipt.Id).OrderBy(line => line.Sequence).ToListAsync(cancellationToken);
        var postedLandedCostLines = await (
            from line in db.LandedCostAllocationLines
            join allocation in db.LandedCostAllocations on line.LandedCostAllocationId equals allocation.Id
            where allocation.CompanyId == companyId && allocation.InventoryReceiptId == receipt.Id && allocation.Status == "Posted"
            select new { line.InventoryReceiptLineId, line.AllocatedAmount, line.BasisQuantity }).ToListAsync(cancellationToken);
        var postedLandedCostPerUnitByReceiptLine = postedLandedCostLines
            .GroupBy(line => line.InventoryReceiptLineId)
            .ToDictionary(group => group.Key, group => group.Sum(line => line.BasisQuantity == 0m ? 0m : line.AllocatedAmount / line.BasisQuantity));
        var requestedIds = requested.Select(line => line.InventoryReceiptLineId).ToArray();
        if (receiptLines.Count(line => requestedIds.Contains(line.Id)) != requestedIds.Length) return TransactionResult.Failure("Every supplier-return line must belong to this receipt.");
        var reserved = await (from line in db.SupplierReturnAuthorizationLines join existingAuthorization in db.SupplierReturnAuthorizations on line.SupplierReturnAuthorizationId equals existingAuthorization.Id where existingAuthorization.CompanyId == companyId && existingAuthorization.Status != "Cancelled" && requestedIds.Contains(line.InventoryReceiptLineId) select new { line.InventoryReceiptLineId, line.AuthorizedQuantity }).ToListAsync(cancellationToken);
        foreach (var item in requested)
        {
            var source = receiptLines.Single(line => line.Id == item.InventoryReceiptLineId);
            var alreadyAuthorized = reserved.Where(line => line.InventoryReceiptLineId == source.Id).Sum(line => line.AuthorizedQuantity);
            if (RoundQuantity(item.Quantity) > source.Quantity - alreadyAuthorized) return TransactionResult.Failure($"Return quantity exceeds the unreserved received quantity for line {source.Sequence}.");
        }
        var order = await db.PurchaseOrders.SingleAsync(item => item.Id == receipt.PurchaseOrderId && item.CompanyId == companyId, cancellationToken);
        var authorization = new SupplierReturnAuthorization { Id = Guid.NewGuid(), CompanyId = companyId, InventoryReceiptId = receipt.Id, PurchaseOrderId = order.Id, VendorId = order.VendorId, ReturnNumber = returnNumber, AuthorizedOn = request.AuthorizedOn, Reason = request.Reason.Trim(), AuthorizedByUserId = ResolveUserId(), AuthorizedAtUtc = DateTimeOffset.UtcNow };
        db.SupplierReturnAuthorizations.Add(authorization);
        db.SupplierReturnAuthorizationLines.AddRange(requested.OrderBy(item => receiptLines.Single(line => line.Id == item.InventoryReceiptLineId).Sequence).Select((item, index) => { var source = receiptLines.Single(line => line.Id == item.InventoryReceiptLineId); return new SupplierReturnAuthorizationLine { Id = Guid.NewGuid(), SupplierReturnAuthorizationId = authorization.Id, InventoryReceiptLineId = source.Id, PurchaseOrderLineId = source.PurchaseOrderLineId, InventoryItemId = source.InventoryItemId, Sequence = index + 1, AuthorizedQuantity = RoundQuantity(item.Quantity), ReceiptUnitCost = source.UnitCost, UnitCost = RoundCurrency(source.UnitCost + postedLandedCostPerUnitByReceiptLine.GetValueOrDefault(source.Id)) }; }));
        receipt.ConcurrencyToken = Guid.NewGuid().ToString("N");
        AddPurchasingAudit(db, companyId, "supplier-return.authorized", nameof(SupplierReturnAuthorization), authorization.Id, new { authorization.ReturnNumber, receipt.ReceiptNumber, authorization.Reason, lines = requested });
        try { await db.SaveChangesAsync(cancellationToken); }
        catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The receipt changed while the supplier return was being authorized. Refresh and try again."); }
        catch (DbUpdateException) { return TransactionResult.Failure("The return number or authorized quantities changed concurrently. Refresh and try again."); }
        return TransactionResult.Success(authorization.Id);
    }

    public async Task<TransactionResult> CancelSupplierReturnAsync(CancelSupplierReturnRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PurchasingManage)) return TransactionResult.Failure("You are not authorized to cancel supplier returns.");
        if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A cancellation reason is required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken);
        var authorization = await db.SupplierReturnAuthorizations.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken);
        if (authorization is null) return TransactionResult.Failure("Supplier-return authorization not found.");
        if (authorization.Status is not ("Open" or "PartiallyShipped")) return TransactionResult.Failure("Only an open supplier return can be cancelled.");
        if (!string.Equals(authorization.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier return changed after it was opened. Refresh and review it again.");
        if (await db.SupplierReturnShipments.AnyAsync(item => item.CompanyId == companyId && item.SupplierReturnAuthorizationId == authorization.Id && item.Status == "Posted", cancellationToken)) return TransactionResult.Failure("Reverse every posted supplier-return shipment before cancelling its authorization.");
        authorization.Status = "Cancelled"; authorization.CancelledByUserId = ResolveUserId(); authorization.CancelledAtUtc = DateTimeOffset.UtcNow; authorization.CancellationReason = request.Reason.Trim(); authorization.ConcurrencyToken = Guid.NewGuid().ToString("N");
        var receipt = await db.InventoryReceipts.SingleAsync(item => item.Id == authorization.InventoryReceiptId && item.CompanyId == companyId, cancellationToken); receipt.ConcurrencyToken = Guid.NewGuid().ToString("N");
        AddPurchasingAudit(db, companyId, "supplier-return.cancelled", nameof(SupplierReturnAuthorization), authorization.Id, new { authorization.ReturnNumber, authorization.CancellationReason });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier return changed while it was being cancelled. Refresh and try again."); }
        return TransactionResult.Success(authorization.Id);
    }

    public async Task<TransactionResult> ShipSupplierReturnAsync(ShipSupplierReturnRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PurchasingManage)) return TransactionResult.Failure("You are not authorized to ship supplier returns.");
        var requested = request.Lines?.Where(line => line.Quantity != 0m).ToArray() ?? [];
        if (string.IsNullOrWhiteSpace(request.ShipmentNumber) || requested.Length == 0 || requested.Any(line => line.SupplierReturnAuthorizationLineId == Guid.Empty || RoundQuantity(line.Quantity) <= 0m) || requested.Select(line => line.SupplierReturnAuthorizationLineId).Distinct().Count() != requested.Length)
            return TransactionResult.Failure("A shipment number and one positive quantity per selected supplier-return line are required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken);
        var authorization = await db.SupplierReturnAuthorizations.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken);
        if (authorization is null) return TransactionResult.Failure("Supplier-return authorization not found.");
        if (authorization.Status is not ("Open" or "PartiallyShipped")) return TransactionResult.Failure("Only an open supplier return can be shipped.");
        if (!string.Equals(authorization.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier return changed after it was opened. Refresh and review it again.");
        if (request.ShippedOn < authorization.AuthorizedOn) return TransactionResult.Failure("The shipment date cannot precede the authorization date.");
        var shipmentNumber = request.ShipmentNumber.Trim(); if (await db.SupplierReturnShipments.AnyAsync(item => item.CompanyId == companyId && item.ShipmentNumber == shipmentNumber, cancellationToken)) return TransactionResult.Failure("Supplier-return shipment number already exists.");
        var lines = await db.SupplierReturnAuthorizationLines.Where(line => line.SupplierReturnAuthorizationId == authorization.Id).OrderBy(line => line.Sequence).ToListAsync(cancellationToken); var requestedIds = requested.Select(line => line.SupplierReturnAuthorizationLineId).ToArray();
        if (lines.Count(line => requestedIds.Contains(line.Id)) != requestedIds.Length) return TransactionResult.Failure("Every shipment line must belong to this supplier-return authorization.");
        foreach (var item in requested) { var line = lines.Single(candidate => candidate.Id == item.SupplierReturnAuthorizationLineId); if (RoundQuantity(item.Quantity) > line.AuthorizedQuantity - line.ShippedQuantity) return TransactionResult.Failure($"Shipment quantity exceeds the remaining authorized quantity for line {line.Sequence}."); }
        var location = await ResolveInventoryLocationAsync(db, companyId, request.WarehouseId, request.BinId, cancellationToken); if (location is null) return TransactionResult.Failure("Select an active warehouse and bin containing the returned goods.");
        var itemIds = lines.Where(line => requestedIds.Contains(line.Id)).Select(line => line.InventoryItemId).Distinct().ToArray(); var items = await db.InventoryItems.Where(item => item.CompanyId == companyId && itemIds.Contains(item.Id)).ToDictionaryAsync(item => item.Id, cancellationToken); if (items.Count != itemIds.Length) return TransactionResult.Failure("One or more returned items are unavailable in this company.");
        var balances = new Dictionary<Guid, InventoryLocationBalance>(); foreach (var itemId in itemIds) balances[itemId] = await GetOrCreateInventoryLocationBalanceAsync(db, companyId, itemId, location.Value.Warehouse.Id, location.Value.Bin.Id, cancellationToken);
        foreach (var group in requested.GroupBy(item => lines.Single(line => line.Id == item.SupplierReturnAuthorizationLineId).InventoryItemId))
        {
            var quantity = group.Sum(item => RoundQuantity(item.Quantity)); var reserved = await db.SalesOrderLines.Where(line => line.InventoryItemId == group.Key && line.AllocationWarehouseId == location.Value.Warehouse.Id && line.AllocationBinId == location.Value.Bin.Id).Select(line => line.AllocatedQuantity).ToListAsync(cancellationToken);
            if (quantity > balances[group.Key].QuantityOnHand - reserved.Sum()) return TransactionResult.Failure("The selected bin does not have enough unreserved stock for this supplier return.");
            var item = items[group.Key]; var returnedValue = group.Sum(entry => RoundCurrency(RoundQuantity(entry.Quantity) * lines.Single(line => line.Id == entry.SupplierReturnAuthorizationLineId).UnitCost)); var remainingQuantity = item.QuantityOnHand - quantity; var remainingValue = RoundCurrency(item.QuantityOnHand * item.UnitCost) - returnedValue;
            if (remainingQuantity < 0m || remainingValue < 0m) return TransactionResult.Failure("Returning these source costs would create a negative inventory quantity or value. Reconcile valuation before shipping the return.");
        }
        var receipt = await db.InventoryReceipts.SingleAsync(item => item.Id == authorization.InventoryReceiptId && item.CompanyId == companyId, cancellationToken); if (receipt.Status != "Posted") return TransactionResult.Failure("The source inventory receipt is no longer posted.");
        var activeBills = await db.VendorBills.Where(item => item.CompanyId == companyId && item.InventoryReceiptId == receipt.Id && item.Status != "Voided").OrderBy(item => item.BillDate).ThenBy(item => item.BillNumber).ToListAsync(cancellationToken);
        var activeBillIds = activeBills.Select(item => item.Id).ToArray();
        var activeBillLines = activeBillIds.Length == 0 ? [] : await db.VendorBillLines.Where(item => activeBillIds.Contains(item.VendorBillId) && item.InventoryReceiptLineId.HasValue && item.MatchedQuantity > 0m).OrderBy(item => item.Sequence).ToListAsync(cancellationToken);
        var priorInvoicedReturns = await (from returnLine in db.SupplierReturnShipmentLines join priorShipment in db.SupplierReturnShipments on returnLine.SupplierReturnShipmentId equals priorShipment.Id where priorShipment.CompanyId == companyId && priorShipment.Status == "Posted" select new { returnLine.InventoryReceiptLineId, returnLine.InvoicedQuantity }).ToListAsync(cancellationToken);
        var returnCalculations = new Dictionary<Guid, (decimal InvoicedQuantity, decimal VendorCreditAmount, decimal GrniReductionAmount)>();
        foreach (var requestedLine in requested)
        {
            var authorizationLine = lines.Single(line => line.Id == requestedLine.SupplierReturnAuthorizationLineId); var returnQuantity = RoundQuantity(requestedLine.Quantity); var remainingReturn = returnQuantity; var priorCredited = priorInvoicedReturns.Where(item => item.InventoryReceiptLineId == authorizationLine.InventoryReceiptLineId).Sum(item => item.InvoicedQuantity); var vendorCredit = 0m;
            foreach (var invoiceLine in activeBillLines.Where(item => item.InventoryReceiptLineId == authorizationLine.InventoryReceiptLineId).OrderBy(item => activeBills.FindIndex(bill => bill.Id == item.VendorBillId)).ThenBy(item => item.Sequence))
            {
                var lineAvailable = invoiceLine.MatchedQuantity; var skipped = Math.Min(lineAvailable, priorCredited); lineAvailable -= skipped; priorCredited -= skipped; if (lineAvailable <= 0m || remainingReturn <= 0m) continue; var creditedQuantity = Math.Min(lineAvailable, remainingReturn); vendorCredit += RoundCurrency(creditedQuantity * invoiceLine.UnitCost); remainingReturn -= creditedQuantity;
            }
            var invoicedQuantity = returnQuantity - remainingReturn; var grniReduction = RoundCurrency(remainingReturn * authorizationLine.ReceiptUnitCost); returnCalculations[authorizationLine.Id] = (invoicedQuantity, vendorCredit, grniReduction);
        }
        var total = requested.Sum(item => RoundCurrency(RoundQuantity(item.Quantity) * lines.Single(line => line.Id == item.SupplierReturnAuthorizationLineId).UnitCost));
        var vendorCreditAmount = returnCalculations.Values.Sum(item => item.VendorCreditAmount); var grniReductionAmount = returnCalculations.Values.Sum(item => item.GrniReductionAmount); var createsCredit = vendorCreditAmount > 0m;
        var bill = createsCredit ? activeBills.FirstOrDefault(item => item.BalanceDue > 0m) ?? activeBills.FirstOrDefault() : null;
        if (createsCredit && bill is null) return TransactionResult.Failure("The invoiced return quantity no longer has an active source vendor bill. Refresh and review the invoice history.");
        var purchaseVarianceAmount = total - vendorCreditAmount - grniReductionAmount;
        if (total <= 0m || vendorCreditAmount < 0m) return TransactionResult.Failure("The supplier-return value must be positive and its vendor-credit value cannot be negative.");
        await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken); var shipmentId = Guid.NewGuid();
        var journalLines = new List<JournalLineRequest>
        {
            new(OperationalRoleReference(AccountingAccountRoles.InventoryAsset), 0m, total, "Inventory returned to supplier")
        };
        if (vendorCreditAmount > 0m) journalLines.Insert(0, new(OperationalRoleReference(AccountingAccountRoles.AccountsPayable), vendorCreditAmount, 0m, "Vendor return credit for invoiced quantity"));
        if (grniReductionAmount > 0m) journalLines.Insert(0, new(OperationalRoleReference(AccountingAccountRoles.GoodsReceivedNotInvoiced), grniReductionAmount, 0m, "Reduce accrual for uninvoiced returned quantity"));
        if (purchaseVarianceAmount > 0m) journalLines.Insert(0, new(OperationalRoleReference(AccountingAccountRoles.PurchasePriceVariance), purchaseVarianceAmount, 0m, "Capitalized cost not recoverable from goods vendor"));
        else if (purchaseVarianceAmount < 0m) journalLines.Insert(0, new(OperationalRoleReference(AccountingAccountRoles.PurchasePriceVariance), 0m, -purchaseVarianceAmount, "Favorable supplier-return variance"));
        var posting = await PostAsync(db, companyId, request.ShippedOn, "Purchasing", shipmentNumber, $"Supplier return {authorization.ReturnNumber}", journalLines, cancellationToken, allowControlAccounts: true, sourceDocumentId: shipmentId, sourceDocumentType: "SupplierReturnShipment", resolveOperationalRoles: true); if (!posting.Succeeded) return posting;
        var sourceApplied = createsCredit ? Math.Min(vendorCreditAmount, bill!.BalanceDue) : 0m; var shipment = new SupplierReturnShipment { Id = shipmentId, CompanyId = companyId, SupplierReturnAuthorizationId = authorization.Id, SourceVendorBillId = bill?.Id, WarehouseId = location.Value.Warehouse.Id, BinId = location.Value.Bin.Id, ShipmentNumber = shipmentNumber, ShippedOn = request.ShippedOn, TotalAmount = total, VendorCreditAmount = vendorCreditAmount, CreatesVendorCredit = createsCredit, SourceAppliedAmount = sourceApplied, AppliedAmount = sourceApplied, JournalEntryId = posting.Id!.Value, ShippedByUserId = ResolveUserId(), ShippedAtUtc = DateTimeOffset.UtcNow }; db.SupplierReturnShipments.Add(shipment);
        var receiptLines = await db.InventoryReceiptLines.Where(line => lines.Select(item => item.InventoryReceiptLineId).Contains(line.Id)).ToDictionaryAsync(line => line.Id, cancellationToken); var order = await db.PurchaseOrders.SingleAsync(item => item.Id == authorization.PurchaseOrderId && item.CompanyId == companyId, cancellationToken); var orderLines = await db.PurchaseOrderLines.Where(line => line.PurchaseOrderId == order.Id).ToDictionaryAsync(line => line.Id, cancellationToken); var sequence = 0;
        foreach (var requestedLine in requested.OrderBy(item => lines.Single(line => line.Id == item.SupplierReturnAuthorizationLineId).Sequence))
        {
            var line = lines.Single(item => item.Id == requestedLine.SupplierReturnAuthorizationLineId); var quantity = RoundQuantity(requestedLine.Quantity); var amount = RoundCurrency(quantity * line.UnitCost); var inventoryItem = items[line.InventoryItemId]; var priorQuantity = inventoryItem.QuantityOnHand; var priorCost = inventoryItem.UnitCost; var resultingQuantity = priorQuantity - quantity; var resultingValue = RoundCurrency(priorQuantity * priorCost) - amount; var resultingCost = resultingQuantity == 0m ? priorCost : RoundCurrency(resultingValue / resultingQuantity);
            var calculation = returnCalculations[line.Id]; inventoryItem.QuantityOnHand = resultingQuantity; inventoryItem.UnitCost = resultingCost; inventoryItem.ConcurrencyToken = Guid.NewGuid().ToString("N"); balances[line.InventoryItemId].QuantityOnHand -= quantity; balances[line.InventoryItemId].ConcurrencyToken = Guid.NewGuid().ToString("N"); line.ShippedQuantity += quantity; receiptLines[line.InventoryReceiptLineId].ReturnedQuantity += quantity; orderLines[line.PurchaseOrderLineId].ReturnedQuantity += quantity; orderLines[line.PurchaseOrderLineId].CreditedQuantity += calculation.InvoicedQuantity;
            db.SupplierReturnShipmentLines.Add(new SupplierReturnShipmentLine { Id = Guid.NewGuid(), SupplierReturnShipmentId = shipment.Id, SupplierReturnAuthorizationLineId = line.Id, InventoryReceiptLineId = line.InventoryReceiptLineId, PurchaseOrderLineId = line.PurchaseOrderLineId, InventoryItemId = line.InventoryItemId, Sequence = ++sequence, Quantity = quantity, UnitCost = line.UnitCost, TotalAmount = amount, InvoicedQuantity = calculation.InvoicedQuantity, GrniReductionAmount = calculation.GrniReductionAmount, VendorCreditUnitCost = calculation.InvoicedQuantity == 0m ? 0m : RoundCurrency(calculation.VendorCreditAmount / calculation.InvoicedQuantity), VendorCreditAmount = calculation.VendorCreditAmount, PriorQuantityOnHand = priorQuantity, PriorUnitCost = priorCost, ResultingUnitCost = resultingCost });
            db.InventoryTransactions.Add(new InventoryTransaction { Id = Guid.NewGuid(), CompanyId = companyId, InventoryItemId = line.InventoryItemId, WarehouseId = location.Value.Warehouse.Id, BinId = location.Value.Bin.Id, OccurredOn = request.ShippedOn, TransactionType = "Supplier return", QuantityChange = -quantity, UnitCost = line.UnitCost, TotalCost = -amount, Reference = shipmentNumber, JournalEntryId = posting.Id });
        }
        if (createsCredit) { bill!.BalanceDue -= sourceApplied; bill.Status = bill.BalanceDue == 0m ? "Paid" : "Partial"; bill.ConcurrencyToken = Guid.NewGuid().ToString("N"); (await db.Vendors.SingleAsync(item => item.Id == authorization.VendorId && item.CompanyId == companyId, cancellationToken)).OpenBalance -= vendorCreditAmount; }
        authorization.Status = lines.All(line => line.ShippedQuantity == line.AuthorizedQuantity) ? "Shipped" : "PartiallyShipped"; authorization.ConcurrencyToken = Guid.NewGuid().ToString("N"); receipt.ConcurrencyToken = Guid.NewGuid().ToString("N"); SetPurchaseOrderReturnStatus(order, orderLines.Values);
        AddPurchasingAudit(db, companyId, "supplier-return.shipped", nameof(SupplierReturnShipment), shipment.Id, new { shipment.ShipmentNumber, authorization.ReturnNumber, inventoryRemovedAmount = shipment.TotalAmount, shipment.VendorCreditAmount, grniReductionAmount, purchaseVarianceAmount, shipment.CreatesVendorCredit, shipment.SourceAppliedAmount, warehouse = location.Value.Warehouse.Code, bin = location.Value.Bin.Code });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier return, inventory, or vendor bill changed while shipping. Refresh and try again."); } catch (DbUpdateException) { return TransactionResult.Failure("The shipment number or supplier-return quantities changed concurrently. Refresh and try again."); }
        await transaction.CommitAsync(cancellationToken); return TransactionResult.Success(shipment.Id);
    }

    public async Task<TransactionResult> ApplySupplierReturnCreditAsync(ApplySupplierReturnCreditRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PayablesManage)) return TransactionResult.Failure("You are not authorized to apply supplier-return credits."); var amount = RoundCurrency(request.Amount); if (amount <= 0m) return TransactionResult.Failure("A positive credit application amount is required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var shipment = await db.SupplierReturnShipments.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnShipmentId && item.CompanyId == companyId, cancellationToken);
        if (shipment is null || shipment.Status != "Posted" || !shipment.CreatesVendorCredit) return TransactionResult.Failure("Only a posted supplier return with vendor credit can be applied."); if (!string.Equals(shipment.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier-return credit changed after it was opened. Refresh and review it again."); if (request.AppliedOn < shipment.ShippedOn) return TransactionResult.Failure("The application date cannot precede the supplier-return shipment date."); if (await IsClosedPeriodAsync(db, companyId, request.AppliedOn, cancellationToken)) return TransactionResult.Failure("The credit application date is in a closed accounting period."); if (amount > shipment.VendorCreditAmount - shipment.AppliedAmount - shipment.RefundedAmount) return TransactionResult.Failure("The application exceeds the available supplier-return credit.");
        var authorization = await db.SupplierReturnAuthorizations.SingleAsync(item => item.Id == shipment.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken); var bill = await db.VendorBills.SingleOrDefaultAsync(item => item.Id == request.VendorBillId && item.CompanyId == companyId && item.VendorId == authorization.VendorId && item.Status != "Voided", cancellationToken); if (bill is null) return TransactionResult.Failure("Select an active bill for the same vendor."); if (amount > bill.BalanceDue) return TransactionResult.Failure("The application exceeds the vendor-bill balance.");
        var application = new SupplierReturnCreditApplication { Id = Guid.NewGuid(), CompanyId = companyId, SupplierReturnShipmentId = shipment.Id, VendorBillId = bill.Id, AppliedOn = request.AppliedOn, Amount = amount, AppliedByUserId = ResolveUserId(), AppliedAtUtc = DateTimeOffset.UtcNow }; db.SupplierReturnCreditApplications.Add(application); shipment.AppliedAmount += amount; shipment.ConcurrencyToken = Guid.NewGuid().ToString("N"); bill.BalanceDue -= amount; bill.Status = bill.BalanceDue == 0m ? "Paid" : "Partial"; bill.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddPurchasingAudit(db, companyId, "supplier-return.credit.applied", nameof(SupplierReturnCreditApplication), application.Id, new { shipment.ShipmentNumber, bill.BillNumber, application.Amount, application.AppliedOn });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier credit or vendor bill changed while applying it. Refresh and try again."); }
        return TransactionResult.Success(application.Id);
    }

    public async Task<TransactionResult> ReverseSupplierReturnCreditApplicationAsync(ReverseSupplierReturnCreditApplicationRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PaymentReverse)) return TransactionResult.Failure("You are not authorized to reverse supplier-credit applications."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A reversal reason is required."); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var application = await db.SupplierReturnCreditApplications.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnCreditApplicationId && item.CompanyId == companyId, cancellationToken);
        if (application is null || application.Status != "Posted") return TransactionResult.Failure("Only a posted supplier-credit application can be reversed."); if (!string.Equals(application.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier-credit application changed after it was opened. Refresh and review it again."); if (request.ReversalDate < application.AppliedOn) return TransactionResult.Failure("The reversal date cannot precede the application date."); if (await IsClosedPeriodAsync(db, companyId, request.ReversalDate, cancellationToken)) return TransactionResult.Failure("The credit-application reversal date is in a closed accounting period.");
        var shipment = await db.SupplierReturnShipments.SingleAsync(item => item.Id == application.SupplierReturnShipmentId && item.CompanyId == companyId, cancellationToken); var bill = await db.VendorBills.SingleAsync(item => item.Id == application.VendorBillId && item.CompanyId == companyId, cancellationToken); application.Status = "Reversed"; application.ReversedByUserId = ResolveUserId(); application.ReversedAtUtc = DateTimeOffset.UtcNow; application.ReversalDate = request.ReversalDate; application.ReversalReason = request.Reason.Trim(); application.ConcurrencyToken = Guid.NewGuid().ToString("N"); shipment.AppliedAmount -= application.Amount; shipment.ConcurrencyToken = Guid.NewGuid().ToString("N"); bill.BalanceDue += application.Amount; bill.Status = bill.BalanceDue == bill.TotalAmount ? "Open" : "Partial"; bill.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddPurchasingAudit(db, companyId, "supplier-return.credit-application.reversed", nameof(SupplierReturnCreditApplication), application.Id, new { shipment.ShipmentNumber, bill.BillNumber, application.Amount, request.ReversalDate, reason = request.Reason.Trim() });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier-credit application changed while reversing. Refresh and try again."); }
        return TransactionResult.Success(application.Id);
    }

    public async Task<TransactionResult> RefundSupplierReturnCreditAsync(RefundSupplierReturnCreditRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PayablesManage)) return TransactionResult.Failure("You are not authorized to record supplier-credit refunds."); var amount = RoundCurrency(request.Amount); if (amount <= 0m || string.IsNullOrWhiteSpace(request.Reference)) return TransactionResult.Failure("A positive refund amount and reference are required."); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var shipment = await db.SupplierReturnShipments.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnShipmentId && item.CompanyId == companyId, cancellationToken);
        if (shipment is null || shipment.Status != "Posted" || !shipment.CreatesVendorCredit) return TransactionResult.Failure("Only a posted supplier return with vendor credit can be refunded."); if (!string.Equals(shipment.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier-return credit changed after it was opened. Refresh and review it again."); if (request.RefundDate < shipment.ShippedOn) return TransactionResult.Failure("The refund date cannot precede the supplier-return shipment date."); if (amount > shipment.VendorCreditAmount - shipment.AppliedAmount - shipment.RefundedAmount) return TransactionResult.Failure("The refund exceeds the available supplier-return credit."); if (await db.SupplierReturnCreditRefunds.AnyAsync(item => item.CompanyId == companyId && item.Reference == request.Reference.Trim(), cancellationToken)) return TransactionResult.Failure("Supplier-credit refund reference already exists.");
        var bank = await db.BankAccounts.SingleOrDefaultAsync(item => item.Id == request.BankAccountId && item.CompanyId == companyId, cancellationToken); if (bank is null) return TransactionResult.Failure("Bank account not found."); var cash = await ResolveBankLedgerAccountNumberAsync(db, companyId, bank, cancellationToken); if (string.IsNullOrWhiteSpace(cash)) return TransactionResult.Failure("The bank account is not mapped to an active ledger account.");
        await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken); var refundId = Guid.NewGuid(); var posting = await PostAsync(db, companyId, request.RefundDate, "Accounts Payable", request.Reference.Trim(), $"Supplier refund for return shipment {shipment.ShipmentNumber}", [new(cash, amount, 0m, "Supplier refund received"), new(OperationalRoleReference(AccountingAccountRoles.AccountsPayable), 0m, amount, "Settle supplier return credit")], cancellationToken, bank.Id, true, refundId, "SupplierReturnCreditRefund", true); if (!posting.Succeeded) return posting;
        var refund = new SupplierReturnCreditRefund { Id = refundId, CompanyId = companyId, SupplierReturnShipmentId = shipment.Id, BankAccountId = bank.Id, Reference = request.Reference.Trim(), RefundDate = request.RefundDate, Amount = amount, JournalEntryId = posting.Id!.Value, RefundedByUserId = ResolveUserId(), RefundedAtUtc = DateTimeOffset.UtcNow }; db.SupplierReturnCreditRefunds.Add(refund); shipment.RefundedAmount += amount; shipment.ConcurrencyToken = Guid.NewGuid().ToString("N"); bank.CurrentBalance += amount; bank.UnreconciledAmount += amount; bank.ConcurrencyToken = Guid.NewGuid().ToString("N"); var authorization = await db.SupplierReturnAuthorizations.SingleAsync(item => item.Id == shipment.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken); (await db.Vendors.SingleAsync(item => item.Id == authorization.VendorId && item.CompanyId == companyId, cancellationToken)).OpenBalance += amount; AddPurchasingAudit(db, companyId, "supplier-return.credit.refunded", nameof(SupplierReturnCreditRefund), refund.Id, new { shipment.ShipmentNumber, refund.Reference, refund.Amount, refund.RefundDate });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier credit or bank account changed while refunding. Refresh and try again."); } catch (DbUpdateException) { return TransactionResult.Failure("The supplier refund reference changed concurrently. Refresh and try again."); }
        await transaction.CommitAsync(cancellationToken); return TransactionResult.Success(refund.Id);
    }

    public async Task<TransactionResult> ReverseSupplierReturnCreditRefundAsync(ReverseSupplierReturnCreditRefundRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PaymentReverse)) return TransactionResult.Failure("You are not authorized to reverse supplier-credit refunds."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A reversal reason is required."); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var refund = await db.SupplierReturnCreditRefunds.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnCreditRefundId && item.CompanyId == companyId, cancellationToken);
        if (refund is null || refund.Status != "Posted") return TransactionResult.Failure("Only a posted supplier-credit refund can be reversed."); if (!string.Equals(refund.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier-credit refund changed after it was opened. Refresh and review it again."); if (request.ReversalDate < refund.RefundDate) return TransactionResult.Failure("The reversal date cannot precede the refund date."); if (await IsInCompletedReconciliationAsync(db, refund.JournalEntryId, cancellationToken)) return TransactionResult.Failure("A reconciled supplier refund cannot be reversed until its bank reconciliation is reopened.");
        await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken); var reversal = await PostInverseAsync(db, companyId, refund.JournalEntryId, request.ReversalDate, $"REV-{refund.Reference}", request.Reason.Trim(), refund.Id, "SupplierReturnCreditRefundReversal", refund.BankAccountId, cancellationToken, "Accounts Payable"); if (!reversal.Succeeded) return reversal; var shipment = await db.SupplierReturnShipments.SingleAsync(item => item.Id == refund.SupplierReturnShipmentId && item.CompanyId == companyId, cancellationToken); var authorization = await db.SupplierReturnAuthorizations.SingleAsync(item => item.Id == shipment.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken); var bank = await db.BankAccounts.SingleAsync(item => item.Id == refund.BankAccountId && item.CompanyId == companyId, cancellationToken); refund.Status = "Reversed"; refund.ReversalJournalEntryId = reversal.Id; refund.ReversedByUserId = ResolveUserId(); refund.ReversedAtUtc = DateTimeOffset.UtcNow; refund.ReversalDate = request.ReversalDate; refund.ReversalReason = request.Reason.Trim(); refund.ConcurrencyToken = Guid.NewGuid().ToString("N"); shipment.RefundedAmount -= refund.Amount; shipment.ConcurrencyToken = Guid.NewGuid().ToString("N"); bank.CurrentBalance -= refund.Amount; bank.UnreconciledAmount += refund.Amount; bank.ConcurrencyToken = Guid.NewGuid().ToString("N"); (await db.Vendors.SingleAsync(item => item.Id == authorization.VendorId && item.CompanyId == companyId, cancellationToken)).OpenBalance -= refund.Amount; AddPurchasingAudit(db, companyId, "supplier-return.credit-refund.reversed", nameof(SupplierReturnCreditRefund), refund.Id, new { refund.Reference, refund.Amount, request.ReversalDate, reason = request.Reason.Trim() });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier refund changed while reversing. Refresh and try again."); }
        await transaction.CommitAsync(cancellationToken); return TransactionResult.Success(refund.Id);
    }

    public async Task<TransactionResult> ReverseSupplierReturnShipmentAsync(ReverseSupplierReturnShipmentRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.PurchasingManage) || !HasPermission(BrassLedgerPermissions.PaymentReverse)) return TransactionResult.Failure("You are not authorized to reverse supplier-return shipments."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A reversal reason is required."); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var shipment = await db.SupplierReturnShipments.SingleOrDefaultAsync(item => item.Id == request.SupplierReturnShipmentId && item.CompanyId == companyId, cancellationToken);
        if (shipment is null || shipment.Status != "Posted") return TransactionResult.Failure("Only a posted supplier-return shipment can be reversed."); if (!string.Equals(shipment.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The supplier-return shipment changed after it was opened. Refresh and review it again."); if (request.ReversalDate < shipment.ShippedOn) return TransactionResult.Failure("The reversal date cannot precede the shipment date."); if (shipment.AppliedAmount != shipment.SourceAppliedAmount || shipment.RefundedAmount != 0m || await db.SupplierReturnCreditApplications.AnyAsync(item => item.CompanyId == companyId && item.SupplierReturnShipmentId == shipment.Id && item.Status == "Posted", cancellationToken) || await db.SupplierReturnCreditRefunds.AnyAsync(item => item.CompanyId == companyId && item.SupplierReturnShipmentId == shipment.Id && item.Status == "Posted", cancellationToken)) return TransactionResult.Failure("Reverse all later supplier-credit applications and refunds before reversing the physical return.");
        var authorization = await db.SupplierReturnAuthorizations.SingleAsync(item => item.Id == shipment.SupplierReturnAuthorizationId && item.CompanyId == companyId, cancellationToken); var receipt = await db.InventoryReceipts.SingleAsync(item => item.Id == authorization.InventoryReceiptId && item.CompanyId == companyId, cancellationToken); if (!shipment.CreatesVendorCredit && await db.VendorBills.AnyAsync(item => item.CompanyId == companyId && item.InventoryReceiptId == receipt.Id && item.Status != "Voided", cancellationToken)) return TransactionResult.Failure("Void the bill matched after this supplier return before reversing its physical shipment.");
        var lines = await db.SupplierReturnShipmentLines.Where(line => line.SupplierReturnShipmentId == shipment.Id).OrderBy(line => line.Sequence).ToListAsync(cancellationToken); var items = await db.InventoryItems.Where(item => item.CompanyId == companyId && lines.Select(line => line.InventoryItemId).Contains(item.Id)).ToDictionaryAsync(item => item.Id, cancellationToken); var finalLineByItem = lines.GroupBy(line => line.InventoryItemId).Select(group => group.OrderByDescending(line => line.Sequence).First()); if (finalLineByItem.Any(line => items[line.InventoryItemId].QuantityOnHand != line.PriorQuantityOnHand - line.Quantity || items[line.InventoryItemId].UnitCost != line.ResultingUnitCost)) return TransactionResult.Failure("This supplier return is no longer the latest valuation event for every item. Post a compensating inventory adjustment instead of rewriting later valuation.");
        await using var transaction = await db.Database.BeginTransactionAsync(cancellationToken); var reversal = await PostInverseAsync(db, companyId, shipment.JournalEntryId, request.ReversalDate, $"REV-{shipment.ShipmentNumber}", request.Reason.Trim(), shipment.Id, "SupplierReturnShipmentReversal", null, cancellationToken, "Purchasing"); if (!reversal.Succeeded) return reversal; var authorizationLines = await db.SupplierReturnAuthorizationLines.Where(line => line.SupplierReturnAuthorizationId == authorization.Id).ToDictionaryAsync(line => line.Id, cancellationToken); var receiptLines = await db.InventoryReceiptLines.Where(line => line.InventoryReceiptId == receipt.Id).ToDictionaryAsync(line => line.Id, cancellationToken); var order = await db.PurchaseOrders.SingleAsync(item => item.Id == authorization.PurchaseOrderId && item.CompanyId == companyId, cancellationToken); var orderLines = await db.PurchaseOrderLines.Where(line => line.PurchaseOrderId == order.Id).ToDictionaryAsync(line => line.Id, cancellationToken);
        foreach (var line in lines.OrderByDescending(line => line.Sequence)) { var item = items[line.InventoryItemId]; item.QuantityOnHand = line.PriorQuantityOnHand; item.UnitCost = line.PriorUnitCost; item.ConcurrencyToken = Guid.NewGuid().ToString("N"); var balance = await GetOrCreateInventoryLocationBalanceAsync(db, companyId, line.InventoryItemId, shipment.WarehouseId, shipment.BinId, cancellationToken); balance.QuantityOnHand += line.Quantity; balance.ConcurrencyToken = Guid.NewGuid().ToString("N"); authorizationLines[line.SupplierReturnAuthorizationLineId].ShippedQuantity -= line.Quantity; receiptLines[line.InventoryReceiptLineId].ReturnedQuantity -= line.Quantity; orderLines[line.PurchaseOrderLineId].ReturnedQuantity -= line.Quantity; orderLines[line.PurchaseOrderLineId].CreditedQuantity -= line.InvoicedQuantity; db.InventoryTransactions.Add(new InventoryTransaction { Id = Guid.NewGuid(), CompanyId = companyId, InventoryItemId = line.InventoryItemId, WarehouseId = shipment.WarehouseId, BinId = shipment.BinId, OccurredOn = request.ReversalDate, TransactionType = "Supplier return reversal", QuantityChange = line.Quantity, UnitCost = line.UnitCost, TotalCost = line.TotalAmount, Reference = $"REV-{shipment.ShipmentNumber}", JournalEntryId = reversal.Id }); }
        if (shipment.CreatesVendorCredit) { var bill = await db.VendorBills.SingleAsync(item => item.Id == shipment.SourceVendorBillId && item.CompanyId == companyId, cancellationToken); bill.BalanceDue += shipment.SourceAppliedAmount; bill.Status = bill.BalanceDue == bill.TotalAmount ? "Open" : "Partial"; bill.ConcurrencyToken = Guid.NewGuid().ToString("N"); (await db.Vendors.SingleAsync(item => item.Id == authorization.VendorId && item.CompanyId == companyId, cancellationToken)).OpenBalance += shipment.VendorCreditAmount; }
        authorization.Status = authorizationLines.Values.All(line => line.ShippedQuantity == 0m) ? "Open" : authorizationLines.Values.All(line => line.ShippedQuantity == line.AuthorizedQuantity) ? "Shipped" : "PartiallyShipped"; authorization.ConcurrencyToken = Guid.NewGuid().ToString("N"); receipt.ConcurrencyToken = Guid.NewGuid().ToString("N"); shipment.Status = "Reversed"; shipment.ReversalJournalEntryId = reversal.Id; shipment.ReversedByUserId = ResolveUserId(); shipment.ReversedAtUtc = DateTimeOffset.UtcNow; shipment.ReversalDate = request.ReversalDate; shipment.ReversalReason = request.Reason.Trim(); shipment.ConcurrencyToken = Guid.NewGuid().ToString("N"); SetPurchaseOrderReturnStatus(order, orderLines.Values); AddPurchasingAudit(db, companyId, "supplier-return.shipment.reversed", nameof(SupplierReturnShipment), shipment.Id, new { shipment.ShipmentNumber, shipment.TotalAmount, shipment.ReversalDate, shipment.ReversalReason });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The supplier return or inventory changed while reversing. Refresh and try again."); }
        await transaction.CommitAsync(cancellationToken); return TransactionResult.Success(shipment.Id);
    }

    private static void SetPurchaseOrderReturnStatus(PurchaseOrder order, IEnumerable<PurchaseOrderLine> lines)
    {
        var materialized = lines.ToArray();
        order.Status = materialized.All(line => line.ReceivedQuantity - line.ReturnedQuantity == line.OrderedQuantity && line.InvoicedQuantity - line.CreditedQuantity == line.OrderedQuantity) ? "Closed" : materialized.All(line => line.ReceivedQuantity - line.ReturnedQuantity == line.OrderedQuantity) ? "Received" : materialized.Any(line => line.ReceivedQuantity - line.ReturnedQuantity > 0m) ? "PartiallyReceived" : "Approved";
        order.ConcurrencyToken = Guid.NewGuid().ToString("N");
    }
}
