using BrassLedger.Application.Accounting;
using BrassLedger.Domain.Accounting;
using BrassLedger.Infrastructure.Auth;
using BrassLedger.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace BrassLedger.Infrastructure.Accounting;

public sealed partial class AccountingTransactionService
{
    public async Task<TransactionResult> CreateInventoryPickAsync(CreateInventoryPickRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.FulfillmentManage)) return TransactionResult.Failure("You are not authorized to create inventory picks.");
        var requested = request.Lines?.Select(line => new { line.SalesOrderLineId, Quantity = RoundQuantity(line.Quantity) }).ToArray() ?? [];
        var pickNumber = request.PickNumber?.Trim() ?? string.Empty;
        if (string.IsNullOrWhiteSpace(pickNumber) || requested.Length == 0 || requested.Any(line => line.SalesOrderLineId == Guid.Empty || line.Quantity <= 0m) || requested.Select(line => line.SalesOrderLineId).Distinct().Count() != requested.Length) return TransactionResult.Failure("Provide a unique pick number and one or more distinct positive line quantities.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken);
        var order = await db.SalesOrders.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.SalesOrderId, cancellationToken); if (order is null) return TransactionResult.Failure("Sales order not found.");
        if (order.Status is not ("Allocated" or "PartiallyShipped")) return TransactionResult.Failure("Only an allocated order can produce a pick ticket.");
        if (request.PickDate < order.OrderedOn) return TransactionResult.Failure("The pick date cannot precede the order date.");
        if (!string.Equals(order.ConcurrencyToken, request.SalesOrderConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The sales order changed after it was opened. Refresh and review it again.");
        if (await db.InventoryPicks.AnyAsync(pick => pick.CompanyId == companyId && pick.PickNumber == pickNumber, cancellationToken)) return TransactionResult.Failure("Pick number already exists.");
        var requestedIds = requested.Select(line => line.SalesOrderLineId).ToArray(); var orderLines = await db.SalesOrderLines.Where(line => line.SalesOrderId == order.Id && requestedIds.Contains(line.Id)).ToDictionaryAsync(line => line.Id, cancellationToken);
        if (orderLines.Count != requestedIds.Length) return TransactionResult.Failure("One or more pick lines are not part of this order.");
        var locations = orderLines.Values.Select(line => new { line.AllocationWarehouseId, line.AllocationBinId }).Distinct().ToArray();
        if (locations.Length != 1 || !locations[0].AllocationWarehouseId.HasValue || !locations[0].AllocationBinId.HasValue) return TransactionResult.Failure("Every pick line must be allocated from the same warehouse and bin.");
        var location = await ResolveInventoryLocationAsync(db, companyId, locations[0].AllocationWarehouseId, locations[0].AllocationBinId, cancellationToken); if (location is null) return TransactionResult.Failure("The allocated warehouse or bin is unavailable.");
        var activeCommitments = await (from line in db.InventoryPickLines join activePick in db.InventoryPicks on line.InventoryPickId equals activePick.Id where activePick.CompanyId == companyId && activePick.SalesOrderId == order.Id && activePick.Status != "Cancelled" && activePick.Status != "Shipped" && requestedIds.Contains(line.SalesOrderLineId) select new { line.SalesOrderLineId, Quantity = activePick.Status == "Draft" ? line.RequestedQuantity : line.PickedQuantity }).ToListAsync(cancellationToken);
        foreach (var line in requested)
            if (line.Quantity + activeCommitments.Where(commitment => commitment.SalesOrderLineId == line.SalesOrderLineId).Sum(commitment => commitment.Quantity) > orderLines[line.SalesOrderLineId].AllocatedQuantity) return TransactionResult.Failure($"Pick quantity exceeds the uncommitted allocation for order line {orderLines[line.SalesOrderLineId].Sequence}.");

        var pick = new InventoryPick { Id = Guid.NewGuid(), CompanyId = companyId, SalesOrderId = order.Id, WarehouseId = location.Value.Warehouse.Id, BinId = location.Value.Bin.Id, PickNumber = pickNumber, PickDate = request.PickDate, CreatedByUserId = ResolveUserId(), CreatedAtUtc = DateTimeOffset.UtcNow };
        db.InventoryPicks.Add(pick); db.InventoryPickLines.AddRange(requested.OrderBy(line => orderLines[line.SalesOrderLineId].Sequence).Select((line, index) => new InventoryPickLine { Id = Guid.NewGuid(), InventoryPickId = pick.Id, SalesOrderLineId = line.SalesOrderLineId, InventoryItemId = orderLines[line.SalesOrderLineId].InventoryItemId, Sequence = index + 1, RequestedQuantity = line.Quantity }));
        order.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "inventory-pick.created", nameof(InventoryPick), pick.Id, new { pick.PickNumber, order.OrderNumber, warehouse = location.Value.Warehouse.Code, bin = location.Value.Bin.Code, lines = requested });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The order allocation changed while the pick was being created. Refresh and try again."); } catch (DbUpdateException) { return TransactionResult.Failure("The pick number or allocation commitment changed concurrently. Refresh and try again."); }
        return TransactionResult.Success(pick.Id);
    }

    public async Task<TransactionResult> CompleteInventoryPickAsync(CompleteInventoryPickRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.FulfillmentManage)) return TransactionResult.Failure("You are not authorized to complete inventory picks.");
        var requested = request.Lines?.Select(line => new { line.InventoryPickLineId, Quantity = RoundQuantity(line.PickedQuantity) }).ToArray() ?? [];
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var pick = await db.InventoryPicks.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.InventoryPickId, cancellationToken); if (pick is null) return TransactionResult.Failure("Inventory pick not found.");
        if (pick.Status != "Draft") return TransactionResult.Failure("Only a draft pick can be completed."); if (!string.Equals(pick.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The inventory pick changed after it was opened. Refresh and review it again.");
        var lines = await db.InventoryPickLines.Where(line => line.InventoryPickId == pick.Id).OrderBy(line => line.Sequence).ToListAsync(cancellationToken);
        if (requested.Length != lines.Count || requested.Select(line => line.InventoryPickLineId).Distinct().Count() != lines.Count || requested.Any(line => line.Quantity < 0m) || requested.All(line => line.Quantity == 0m) || requested.Any(line => lines.All(candidate => candidate.Id != line.InventoryPickLineId))) return TransactionResult.Failure("Report one non-negative picked quantity for every pick line, with at least one unit picked.");
        foreach (var line in lines) { var quantity = requested.Single(candidate => candidate.InventoryPickLineId == line.Id).Quantity; if (quantity > line.RequestedQuantity) return TransactionResult.Failure($"Picked quantity exceeds the request for pick line {line.Sequence}."); line.PickedQuantity = quantity; }
        pick.Status = "Picked"; pick.CompletedByUserId = ResolveUserId(); pick.CompletedAtUtc = DateTimeOffset.UtcNow; pick.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "inventory-pick.completed", nameof(InventoryPick), pick.Id, new { pick.PickNumber, lines = requested });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The inventory pick changed while it was being completed. Refresh and try again."); }
        return TransactionResult.Success(pick.Id);
    }

    public async Task<TransactionResult> CancelInventoryPickAsync(CancelInventoryPickRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.FulfillmentManage)) return TransactionResult.Failure("You are not authorized to cancel inventory picks."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A pick cancellation reason is required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var pick = await db.InventoryPicks.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.InventoryPickId, cancellationToken); if (pick is null) return TransactionResult.Failure("Inventory pick not found.");
        if (pick.Status is not ("Draft" or "Picked")) return TransactionResult.Failure("Only an unpacked draft or completed pick can be cancelled."); if (!string.Equals(pick.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The inventory pick changed after it was opened. Refresh and review it again.");
        if (await db.InventoryPackingSlips.AnyAsync(pack => pack.InventoryPickId == pick.Id && pack.Status != "Cancelled", cancellationToken)) return TransactionResult.Failure("Cancel every active packing slip before cancelling this pick.");
        pick.Status = "Cancelled"; pick.CancelledByUserId = ResolveUserId(); pick.CancelledAtUtc = DateTimeOffset.UtcNow; pick.CancellationReason = request.Reason.Trim(); pick.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "inventory-pick.cancelled", nameof(InventoryPick), pick.Id, new { pick.PickNumber, pick.CancellationReason });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The inventory pick changed while it was being cancelled. Refresh and try again."); } return TransactionResult.Success(pick.Id);
    }

    public async Task<TransactionResult> PackInventoryPickAsync(PackInventoryPickRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.FulfillmentManage)) return TransactionResult.Failure("You are not authorized to pack inventory picks."); var packingNumber = request.PackingSlipNumber?.Trim() ?? string.Empty; var requested = request.Lines?.Select(line => new { line.InventoryPickLineId, Quantity = RoundQuantity(line.Quantity) }).ToArray() ?? [];
        if (string.IsNullOrWhiteSpace(packingNumber) || requested.Length == 0 || requested.Any(line => line.Quantity <= 0m) || requested.Select(line => line.InventoryPickLineId).Distinct().Count() != requested.Length) return TransactionResult.Failure("Provide a unique packing-slip number and one or more distinct positive quantities.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var pick = await db.InventoryPicks.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.InventoryPickId, cancellationToken); if (pick is null) return TransactionResult.Failure("Inventory pick not found.");
        if (pick.Status is not ("Picked" or "PartiallyPacked")) return TransactionResult.Failure("Only a completed pick with unpacked quantity can be packed."); if (!string.Equals(pick.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The inventory pick changed after it was opened. Refresh and review it again."); if (await db.InventoryPackingSlips.AnyAsync(pack => pack.CompanyId == companyId && pack.PackingSlipNumber == packingNumber, cancellationToken)) return TransactionResult.Failure("Packing-slip number already exists.");
        if (request.PackedOn < pick.PickDate) return TransactionResult.Failure("The packing date cannot precede the pick date.");
        var pickLines = await db.InventoryPickLines.Where(line => line.InventoryPickId == pick.Id).ToDictionaryAsync(line => line.Id, cancellationToken); if (requested.Any(line => !pickLines.ContainsKey(line.InventoryPickLineId))) return TransactionResult.Failure("One or more packing lines are not part of this pick.");
        var alreadyPacked = await (from line in db.InventoryPackingSlipLines join activePack in db.InventoryPackingSlips on line.InventoryPackingSlipId equals activePack.Id where activePack.InventoryPickId == pick.Id && activePack.Status != "Cancelled" select new { line.InventoryPickLineId, line.Quantity }).ToListAsync(cancellationToken);
        foreach (var line in requested) if (line.Quantity + alreadyPacked.Where(packed => packed.InventoryPickLineId == line.InventoryPickLineId).Sum(packed => packed.Quantity) > pickLines[line.InventoryPickLineId].PickedQuantity) return TransactionResult.Failure($"Packing quantity exceeds picked quantity for line {pickLines[line.InventoryPickLineId].Sequence}.");
        var pack = new InventoryPackingSlip { Id = Guid.NewGuid(), CompanyId = companyId, SalesOrderId = pick.SalesOrderId, InventoryPickId = pick.Id, WarehouseId = pick.WarehouseId, BinId = pick.BinId, PackingSlipNumber = packingNumber, PackedOn = request.PackedOn, PackedByUserId = ResolveUserId(), PackedAtUtc = DateTimeOffset.UtcNow };
        db.InventoryPackingSlips.Add(pack); db.InventoryPackingSlipLines.AddRange(requested.OrderBy(line => pickLines[line.InventoryPickLineId].Sequence).Select((line, index) => new InventoryPackingSlipLine { Id = Guid.NewGuid(), InventoryPackingSlipId = pack.Id, InventoryPickLineId = line.InventoryPickLineId, SalesOrderLineId = pickLines[line.InventoryPickLineId].SalesOrderLineId, InventoryItemId = pickLines[line.InventoryPickLineId].InventoryItemId, Sequence = index + 1, Quantity = line.Quantity }));
        var requestedByLine = requested.ToDictionary(line => line.InventoryPickLineId, line => line.Quantity); pick.Status = pickLines.Values.All(line => alreadyPacked.Where(packed => packed.InventoryPickLineId == line.Id).Sum(packed => packed.Quantity) + requestedByLine.GetValueOrDefault(line.Id) == line.PickedQuantity) ? "Packed" : "PartiallyPacked"; pick.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "inventory-packing-slip.created", nameof(InventoryPackingSlip), pack.Id, new { pack.PackingSlipNumber, pick.PickNumber, lines = requested });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The inventory pick changed while it was being packed. Refresh and try again."); } catch (DbUpdateException) { return TransactionResult.Failure("The packing-slip number or picked quantity changed concurrently. Refresh and try again."); } return TransactionResult.Success(pack.Id);
    }

    public async Task<TransactionResult> CancelInventoryPackingSlipAsync(CancelInventoryPackingSlipRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.FulfillmentManage)) return TransactionResult.Failure("You are not authorized to cancel packing slips."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A packing-slip cancellation reason is required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var pack = await db.InventoryPackingSlips.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.InventoryPackingSlipId, cancellationToken); if (pack is null) return TransactionResult.Failure("Packing slip not found.");
        if (pack.Status != "Packed") return TransactionResult.Failure("Only an unshipped packing slip can be cancelled."); if (!string.Equals(pack.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The packing slip changed after it was opened. Refresh and review it again.");
        pack.Status = "Cancelled"; pack.CancelledByUserId = ResolveUserId(); pack.CancelledAtUtc = DateTimeOffset.UtcNow; pack.CancellationReason = request.Reason.Trim(); pack.ConcurrencyToken = Guid.NewGuid().ToString("N"); var pick = await db.InventoryPicks.SingleAsync(candidate => candidate.Id == pack.InventoryPickId, cancellationToken); var pickLines = await db.InventoryPickLines.Where(line => line.InventoryPickId == pick.Id).ToListAsync(cancellationToken); var otherPacked = await (from line in db.InventoryPackingSlipLines join other in db.InventoryPackingSlips on line.InventoryPackingSlipId equals other.Id where other.InventoryPickId == pick.Id && other.Id != pack.Id && other.Status != "Cancelled" select new { line.InventoryPickLineId, line.Quantity }).ToListAsync(cancellationToken); pick.Status = otherPacked.Count == 0 ? "Picked" : pickLines.All(line => otherPacked.Where(packed => packed.InventoryPickLineId == line.Id).Sum(packed => packed.Quantity) == line.PickedQuantity) ? "Packed" : "PartiallyPacked"; pick.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "inventory-packing-slip.cancelled", nameof(InventoryPackingSlip), pack.Id, new { pack.PackingSlipNumber, pack.CancellationReason });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The packing slip or pick changed while it was being cancelled. Refresh and try again."); } return TransactionResult.Success(pack.Id);
    }

    public async Task<TransactionResult> PromiseSalesOrderBackorderAsync(PromiseSalesOrderBackorderRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.SalesManage)) return TransactionResult.Failure("You are not authorized to promise sales backorders."); var quantity = RoundQuantity(request.Quantity); if (quantity <= 0m || string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A positive backorder quantity and reason are required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var order = await db.SalesOrders.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.SalesOrderId, cancellationToken); if (order is null) return TransactionResult.Failure("Sales order not found.");
        if (order.Status is not ("Approved" or "Allocated" or "PartiallyShipped")) return TransactionResult.Failure("Only approved open demand can be promised as a backorder."); if (!string.Equals(order.ConcurrencyToken, request.SalesOrderConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The sales order changed after it was opened. Refresh and review it again."); if (request.PromisedShipOn < DateOnly.FromDateTime(DateTime.Today)) return TransactionResult.Failure("The promised ship date cannot be in the past.");
        var line = await db.SalesOrderLines.SingleOrDefaultAsync(candidate => candidate.SalesOrderId == order.Id && candidate.Id == request.SalesOrderLineId, cancellationToken); if (line is null) return TransactionResult.Failure("Sales-order line not found."); var outstandingPromises = await db.SalesOrderBackorderPromises.Where(backorder => backorder.CompanyId == companyId && backorder.SalesOrderLineId == line.Id && backorder.Status != "Cancelled" && backorder.Status != "Fulfilled").Select(backorder => backorder.PromisedQuantity - backorder.FulfilledQuantity).ToListAsync(cancellationToken); var availableDemand = line.OrderedQuantity - line.ShippedQuantity - line.CancelledQuantity - line.AllocatedQuantity - outstandingPromises.Sum(); if (quantity > availableDemand) return TransactionResult.Failure("Backorder promise exceeds open, unallocated, and unpromised demand.");
        var promise = new SalesOrderBackorderPromise { Id = Guid.NewGuid(), CompanyId = companyId, SalesOrderId = order.Id, SalesOrderLineId = line.Id, PromisedQuantity = quantity, PromisedShipOn = request.PromisedShipOn, Reason = request.Reason.Trim(), CreatedByUserId = ResolveUserId(), CreatedAtUtc = DateTimeOffset.UtcNow }; db.SalesOrderBackorderPromises.Add(promise); order.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "sales-order.backorder.promised", nameof(SalesOrderBackorderPromise), promise.Id, new { order.OrderNumber, line.Sequence, promise.PromisedQuantity, promise.PromisedShipOn, promise.Reason });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The sales order changed while the backorder was being promised. Refresh and try again."); } return TransactionResult.Success(promise.Id);
    }

    public async Task<TransactionResult> CancelSalesOrderBackorderAsync(CancelSalesOrderBackorderRequest request, CancellationToken cancellationToken = default)
    {
        if (!HasPermission(BrassLedgerPermissions.SalesManage)) return TransactionResult.Failure("You are not authorized to cancel sales backorders."); if (string.IsNullOrWhiteSpace(request.Reason)) return TransactionResult.Failure("A backorder cancellation reason is required.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var promise = await db.SalesOrderBackorderPromises.SingleOrDefaultAsync(candidate => candidate.CompanyId == companyId && candidate.Id == request.SalesOrderBackorderPromiseId, cancellationToken); if (promise is null) return TransactionResult.Failure("Backorder promise not found."); if (promise.Status is not ("Open" or "PartiallyFulfilled")) return TransactionResult.Failure("Only an outstanding backorder promise can be cancelled."); if (!string.Equals(promise.ConcurrencyToken, request.ConcurrencyToken, StringComparison.Ordinal)) return TransactionResult.Failure("The backorder promise changed after it was opened. Refresh and review it again.");
        promise.Status = "Cancelled"; promise.CancelledByUserId = ResolveUserId(); promise.CancelledAtUtc = DateTimeOffset.UtcNow; promise.CancellationReason = request.Reason.Trim(); promise.ConcurrencyToken = Guid.NewGuid().ToString("N"); AddSalesFulfillmentAudit(db, companyId, "sales-order.backorder.cancelled", nameof(SalesOrderBackorderPromise), promise.Id, new { promise.CancellationReason, outstandingQuantity = promise.PromisedQuantity - promise.FulfilledQuantity }); try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The backorder promise changed while it was being cancelled. Refresh and try again."); } return TransactionResult.Success(promise.Id);
    }
}
