using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BrassLedger.Application.Accounting;
using BrassLedger.Domain.Accounting;
using BrassLedger.Infrastructure.Auth;
using BrassLedger.Infrastructure.Persistence;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;

namespace BrassLedger.Infrastructure.Accounting;

public sealed class SsaOriginalWageFileService(IDbContextFactory<BrassLedgerDbContext> dbContextFactory, IHttpContextAccessor httpContextAccessor) : ISsaOriginalWageFileService
{
    private const string FileKind = "EFW2";
    public const string SupportedLayoutCode = "EFW2-2026-512-RA-RE-RW-RO-RT-RU-RF";
    public const int SupportedSpecificationTaxYear = 2026;
    public static readonly DateOnly SupportedPublicationDate = new(2026, 7, 7);

    public async Task<SsaOriginalWageFileWorkspace> GetAsync(CancellationToken cancellationToken = default)
    {
        RequireSensitive(); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken);
        var configurations = await db.PayrollSsaWageFileConfigurations.AsNoTracking().Where(item => item.CompanyId == companyId && item.FileKind == FileKind).OrderByDescending(item => item.SpecificationTaxYear).ToListAsync(cancellationToken);
        var files = await db.PayrollSsaOriginalWageFiles.AsNoTracking().Where(item => item.CompanyId == companyId).ToListAsync(cancellationToken);
        return new(configurations.Select(ToSnapshot).ToArray(), files.OrderByDescending(item => item.GeneratedAtUtc).Select(ToSnapshot).ToArray());
    }

    public async Task<TransactionResult> SaveConfigurationAsync(SaveSsaOriginalWageFileConfigurationRequest request, CancellationToken cancellationToken = default)
    {
        if (!Has(BrassLedgerPermissions.PayrollPrepare) || !Has(BrassLedgerPermissions.PayrollSensitiveData)) return TransactionResult.Failure("You are not authorized to prepare protected SSA original wage-file settings.");
        if (request.IsApproved && !Has(BrassLedgerPermissions.PayrollApprove)) return TransactionResult.Failure("Payroll approval permission is required to approve an SSA specification.");
        var sourceUrl = request.OfficialSpecificationUrl?.Trim() ?? string.Empty; var digest = request.OfficialSpecificationSha256?.Trim().ToLowerInvariant() ?? string.Empty; var notes = request.ReviewNotes?.Trim() ?? string.Empty;
        if (request.SpecificationTaxYear is < 1978 or > 2100) return TransactionResult.Failure("Enter a valid SSA specification tax year.");
        var expectedFile = $"{request.SpecificationTaxYear % 100:00}efw2.pdf"; if (!Uri.TryCreate(sourceUrl, UriKind.Absolute, out var uri) || uri.Scheme != "https" || !(uri.Host.Equals("ssa.gov", StringComparison.OrdinalIgnoreCase) || uri.Host.EndsWith(".ssa.gov", StringComparison.OrdinalIgnoreCase)) || !uri.AbsolutePath.EndsWith(expectedFile, StringComparison.OrdinalIgnoreCase)) return TransactionResult.Failure($"Use the exact official SSA {request.SpecificationTaxYear} EFW2 PDF URL ending in {expectedFile}.");
        if (request.SourceRetrievedOn == default || request.SourceRetrievedOn > DateOnly.FromDateTime(DateTime.Today)) return TransactionResult.Failure("Enter the actual specification retrieval date; it cannot be in the future.");
        if (request.IsActive && !request.IsApproved) return TransactionResult.Failure("Only an approved SSA specification can be active.");
        if (request.IsApproved && request.SpecificationTaxYear != SupportedSpecificationTaxYear) return TransactionResult.Failure($"The original-file encoder has no reviewed layout for SSA tax year {request.SpecificationTaxYear}; retain it as an inactive draft.");
        if (request.IsApproved && request.SourceRetrievedOn < SupportedPublicationDate) return TransactionResult.Failure($"The reviewed SSA tax year 2026 EFW2 publication was issued on {SupportedPublicationDate:yyyy-MM-dd}; the retrieval date cannot precede it.");
        if (request.IsApproved && (request.LayoutCompatibilityCode != SupportedLayoutCode || digest.Length != 64 || digest.Any(character => !Uri.IsHexDigit(character)) || notes.Length < 30)) return TransactionResult.Failure("Approval requires the supported reviewed layout code, the official PDF SHA-256, and substantive review notes.");
        var submitter = ToSubmitter(request); var validation = SsaEfw2FileBuilder.Build(ValidationPackage(request.SpecificationTaxYear), submitter); if (!validation.Succeeded) return TransactionResult.Failure(string.Join(" ", validation.Errors));
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); PayrollSsaWageFileConfiguration entity;
        if (request.Id.HasValue) { entity = await db.PayrollSsaWageFileConfigurations.SingleOrDefaultAsync(item => item.Id == request.Id && item.CompanyId == companyId && item.FileKind == FileKind, cancellationToken) ?? new(); if (entity.Id == Guid.Empty) return TransactionResult.Failure("SSA EFW2 configuration not found."); if (entity.ConcurrencyToken != request.ConcurrencyToken) return TransactionResult.Failure("The SSA configuration changed after it was opened. Refresh and try again."); }
        else { if (await db.PayrollSsaWageFileConfigurations.AnyAsync(item => item.CompanyId == companyId && item.SpecificationTaxYear == request.SpecificationTaxYear && item.FileKind == FileKind, cancellationToken)) return TransactionResult.Failure("This company already has an SSA EFW2 configuration for that tax year."); entity = new() { Id = Guid.NewGuid(), CompanyId = companyId, FileKind = FileKind }; db.Add(entity); }
        Apply(entity, request, sourceUrl, digest, notes); entity.ApprovedByUserId = request.IsApproved ? ResolveUserId() : null; entity.ApprovedAtUtc = request.IsApproved ? DateTimeOffset.UtcNow : null; entity.ConcurrencyToken = Guid.NewGuid().ToString("N"); Audit(db, companyId, request.Id.HasValue ? "ssa-efw2.configuration.updated" : "ssa-efw2.configuration.created", entity.Id, new { entity.SpecificationTaxYear, entity.SpecificationVersion, entity.LayoutCompatibilityCode, entity.OfficialSpecificationUrl, entity.OfficialSpecificationSha256, entity.SourceRetrievedOn, entity.ReviewNotes, entity.KindOfEmployer, entity.EmploymentCode, hasEmployerSignaturePin = !string.IsNullOrEmpty(entity.EmployerSignaturePin), entity.IsApproved, entity.IsActive });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The SSA configuration changed while saving. Refresh and try again."); } catch (DbUpdateException) { return TransactionResult.Failure("The SSA EFW2 specification tax year conflicts with an existing company configuration."); }
        return TransactionResult.Success(entity.Id);
    }

    public async Task<TransactionResult> GenerateAsync(GenerateSsaOriginalWageFileRequest request, CancellationToken cancellationToken = default)
    {
        if (!Has(BrassLedgerPermissions.PayrollPrepare) || !Has(BrassLedgerPermissions.PayrollSensitiveData)) return TransactionResult.Failure("You are not authorized to generate protected SSA original wage files.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var filing = await db.PayrollFilings.AsNoTracking().SingleOrDefaultAsync(item => item.Id == request.PayrollFilingId && item.CompanyId == companyId && item.FormCode == "W2" && item.Status == "Approved" && item.ApprovedSourceDigestSha256 != "", cancellationToken); if (filing is null) return TransactionResult.Failure("Select a currently approved source-locked W-2/W-3 filing from this company.");
        if (await db.PayrollSsaOriginalWageFiles.AnyAsync(item => item.CompanyId == companyId && item.PayrollFilingId == filing.Id, cancellationToken)) return TransactionResult.Failure("An immutable original SSA wage file already exists for this filing.");
        var configuration = await db.PayrollSsaWageFileConfigurations.AsNoTracking().SingleOrDefaultAsync(item => item.CompanyId == companyId && item.SpecificationTaxYear == filing.TaxYear && item.FileKind == FileKind && item.IsApproved && item.IsActive, cancellationToken); if (configuration is null) return TransactionResult.Failure($"No approved active SSA EFW2 specification exists for tax year {filing.TaxYear}; do not reuse another year's layout.");
        if (configuration.LayoutCompatibilityCode != SupportedLayoutCode) return TransactionResult.Failure("The active SSA EFW2 configuration was approved for an older encoder layout. Re-review and approve the current layout before generation.");
        var package = JsonSerializer.Deserialize<W2PackageData>(filing.ApprovedDataJson) ?? new(); var built = SsaEfw2FileBuilder.Build(package, ToSubmitter(configuration)); if (!built.Succeeded) return TransactionResult.Failure(string.Join(" ", built.Errors));
        var contentHash = Hash(built.Content); var sourceHash = Hash(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new { filingId = filing.Id, filing.ApprovedSourceDigestSha256, filing.ApprovedDataJson, configurationId = configuration.Id, configuration.ConcurrencyToken, configuration.OfficialSpecificationSha256 })));
        var file = new PayrollSsaOriginalWageFile { Id = Guid.NewGuid(), CompanyId = companyId, PayrollFilingId = filing.Id, PayrollSsaWageFileConfigurationId = configuration.Id, TaxYear = filing.TaxYear, FileName = $"EFW2-{filing.TaxYear}.txt", ContentBase64 = Convert.ToBase64String(built.Content), ContentSha256 = contentHash, SourceDigestSha256 = sourceHash, SpecificationVersion = configuration.SpecificationVersion, Status = "GeneratedForAccuWage", RecordCount = built.RecordCount, EmployeeRecordCount = built.EmployeeRecordCount, GeneratedByUserId = ResolveUserId(), GeneratedAtUtc = DateTimeOffset.UtcNow, ConcurrencyToken = Guid.NewGuid().ToString("N") }; db.Add(file); Audit(db, companyId, "ssa-efw2.generated", file.Id, new { filing.Id, file.TaxYear, file.FileName, file.ContentSha256, file.SourceDigestSha256, file.SpecificationVersion, file.RecordCount, file.EmployeeRecordCount, file.Status });
        try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateException) { return TransactionResult.Failure("An SSA EFW2 wage file was already generated for this filing."); }
        return TransactionResult.Success(file.Id);
    }

    public async Task<TransactionResult> RecordValidationAsync(RecordSsaWageFileValidationRequest request, CancellationToken cancellationToken = default)
    {
        if (!Has(BrassLedgerPermissions.PayrollApprove) || !Has(BrassLedgerPermissions.PayrollSensitiveData)) return TransactionResult.Failure("You are not authorized to record AccuWage review of protected wage files."); var evidence = request.EvidenceReference?.Trim() ?? string.Empty; var notes = request.Notes?.Trim() ?? string.Empty; if (evidence.Length < 5 || notes.Length < 20) return TransactionResult.Failure("Retain the AccuWage evidence reference and substantive validation notes.");
        await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var file = await db.PayrollSsaOriginalWageFiles.SingleOrDefaultAsync(item => item.Id == request.FileId && item.CompanyId == companyId, cancellationToken); if (file is null) return TransactionResult.Failure("SSA original wage file not found."); if (file.Status != "GeneratedForAccuWage") return TransactionResult.Failure("AccuWage outcome has already been recorded for this immutable file."); if (file.ConcurrencyToken != request.ConcurrencyToken) return TransactionResult.Failure("The wage file changed after it was opened. Refresh and try again."); file.Status = request.Passed ? "AccuWageValidated" : "AccuWageRejected"; file.AccuWageEvidenceReference = evidence; file.ValidationNotes = notes; file.ValidatedByUserId = ResolveUserId(); file.ValidatedAtUtc = DateTimeOffset.UtcNow; file.ConcurrencyToken = Guid.NewGuid().ToString("N"); Audit(db, companyId, "ssa-efw2.accuwage-recorded", file.Id, new { file.Status, file.AccuWageEvidenceReference, file.ValidationNotes, file.ContentSha256 }); try { await db.SaveChangesAsync(cancellationToken); } catch (DbUpdateConcurrencyException) { return TransactionResult.Failure("The wage file changed while validation was recorded. Refresh and try again."); }
        return TransactionResult.Success(file.Id);
    }

    public async Task<SsaWageFileDownload?> DownloadAsync(Guid fileId, CancellationToken cancellationToken = default) { RequireSensitive(); await using var db = await dbContextFactory.CreateDbContextAsync(cancellationToken); var companyId = await ResolveCompanyIdAsync(db, cancellationToken); var file = await db.PayrollSsaOriginalWageFiles.AsNoTracking().SingleOrDefaultAsync(item => item.Id == fileId && item.CompanyId == companyId, cancellationToken); if (file is null) return null; var bytes = Convert.FromBase64String(file.ContentBase64); if (Hash(bytes) != file.ContentSha256) throw new InvalidOperationException("Stored SSA original wage-file integrity validation failed."); return new(file.FileName, bytes, file.ContentSha256, file.Status); }

    private static W2PackageData ValidationPackage(int year) { var employee = new W2EmployeeData(Guid.Empty, "TEST", "Test Employee", "123456789", "1 Main St", "", "12345", 1, 1, 1, .06m, 1, .01m, [], "Test", "", "Employee", "Anytown", "MI"); return new(TaxYear: year, EmployerLegalName: "VALIDATION EMPLOYER", EmployerEin: "123456789", Employees: [employee], W3Box1Total: 1, W3Box2Total: 1, W3Box3Total: 1, W3Box4Total: .06m, W3Box5Total: 1, W3Box6Total: .01m); }
    private static SsaEfw2Submitter ToSubmitter(SaveSsaOriginalWageFileConfigurationRequest x) => new(x.SpecificationTaxYear, x.SpecificationVersion, x.OfficialSpecificationUrl, x.SubmitterEin, x.BsoUserId, x.SubmitterName, x.LocationAddress, x.DeliveryAddress, x.City, x.State, x.PostalCode, x.ContactName, x.ContactPhone, x.ContactEmail, x.PreparerCode, x.EmployerLocationAddress, x.EmployerDeliveryAddress, x.EmployerCity, x.EmployerState, x.EmployerPostalCode, x.EmployerContactName, x.EmployerContactPhone, x.EmployerContactEmail, x.KindOfEmployer, x.EmploymentCode, x.EmployerSignaturePin);
    private static SsaEfw2Submitter ToSubmitter(PayrollSsaWageFileConfiguration x) => new(x.SpecificationTaxYear, x.SpecificationVersion, x.OfficialSpecificationUrl, x.SubmitterEin, x.BsoUserId, x.SubmitterName, x.LocationAddress, x.DeliveryAddress, x.City, x.State, x.PostalCode, x.ContactName, x.ContactPhone, x.ContactEmail, x.PreparerCode, x.EmployerLocationAddress, x.EmployerDeliveryAddress, x.EmployerCity, x.EmployerState, x.EmployerPostalCode, x.EmployerContactName, x.EmployerContactPhone, x.EmployerContactEmail, x.KindOfEmployer, x.EmploymentCode, x.EmployerSignaturePin);
    private static SsaOriginalWageFileConfigurationSnapshot ToSnapshot(PayrollSsaWageFileConfiguration x) => new(x.Id, ToSubmitter(x), x.LayoutCompatibilityCode, x.OfficialSpecificationSha256, x.SourceRetrievedOn, x.ReviewNotes, x.IsApproved, x.ApprovedAtUtc, x.IsActive, x.ConcurrencyToken);
    private static SsaOriginalWageFileSnapshot ToSnapshot(PayrollSsaOriginalWageFile x) => new(x.Id, x.PayrollFilingId, x.TaxYear, x.FileName, x.ContentSha256, x.SourceDigestSha256, x.SpecificationVersion, x.Status, x.RecordCount, x.EmployeeRecordCount, x.GeneratedAtUtc, x.ValidatedAtUtc, x.AccuWageEvidenceReference, x.ValidationNotes, x.ConcurrencyToken);
    private static void Apply(PayrollSsaWageFileConfiguration x, SaveSsaOriginalWageFileConfigurationRequest r, string url, string digest, string notes) { x.FileKind = FileKind; x.SpecificationTaxYear = r.SpecificationTaxYear; x.SpecificationVersion = r.SpecificationVersion.Trim(); x.LayoutCompatibilityCode = r.LayoutCompatibilityCode.Trim(); x.OfficialSpecificationUrl = url; x.OfficialSpecificationSha256 = digest; x.SourceRetrievedOn = r.SourceRetrievedOn; x.ReviewNotes = notes; x.SubmitterEin = r.SubmitterEin.Trim(); x.BsoUserId = r.BsoUserId.Trim(); x.SubmitterName = r.SubmitterName.Trim(); x.LocationAddress = r.LocationAddress.Trim(); x.DeliveryAddress = r.DeliveryAddress.Trim(); x.City = r.City.Trim(); x.State = r.State.Trim().ToUpperInvariant(); x.PostalCode = r.PostalCode.Trim(); x.ContactName = r.ContactName.Trim(); x.ContactPhone = r.ContactPhone.Trim(); x.ContactEmail = r.ContactEmail.Trim(); x.PreparerCode = r.PreparerCode.Trim().ToUpperInvariant(); x.EmployerLocationAddress = r.EmployerLocationAddress.Trim(); x.EmployerDeliveryAddress = r.EmployerDeliveryAddress.Trim(); x.EmployerCity = r.EmployerCity.Trim(); x.EmployerState = r.EmployerState.Trim().ToUpperInvariant(); x.EmployerPostalCode = r.EmployerPostalCode.Trim(); x.EmployerContactName = r.EmployerContactName.Trim(); x.EmployerContactPhone = r.EmployerContactPhone.Trim(); x.EmployerContactEmail = r.EmployerContactEmail.Trim(); x.KindOfEmployer = r.KindOfEmployer.Trim().ToUpperInvariant(); x.EmploymentCode = r.EmploymentCode.Trim().ToUpperInvariant(); x.EmployerSignaturePin = r.EmployerSignaturePin.Trim(); x.IsApproved = r.IsApproved; x.IsActive = r.IsActive; }
    private static string Hash(byte[] value) => Convert.ToHexString(SHA256.HashData(value)).ToLowerInvariant(); private bool Has(string permission) => httpContextAccessor.HttpContext is null || httpContextAccessor.HttpContext.User.HasClaim(BrassLedgerAuthenticationDefaults.PermissionClaimType, permission); private void RequireSensitive() { if (!Has(BrassLedgerPermissions.PayrollSensitiveData)) throw new UnauthorizedAccessException("You are not authorized to view protected SSA wage files."); }
    private Guid? ResolveUserId() => Guid.TryParse(httpContextAccessor.HttpContext?.User.FindFirstValue(ClaimTypes.NameIdentifier), out var id) ? id : null;
    private async Task<Guid> ResolveCompanyIdAsync(BrassLedgerDbContext db, CancellationToken token) { var context = httpContextAccessor.HttpContext; var claim = context?.User.FindFirstValue(BrassLedgerAuthenticationDefaults.CompanyIdClaimType); if (context is not null && !Guid.TryParse(claim, out _)) throw new UnauthorizedAccessException("An authenticated company context is required."); if (Guid.TryParse(claim, out var id) && await db.Companies.AnyAsync(x => x.Id == id, token)) return id; return await db.Companies.OrderBy(x => x.Name).Select(x => x.Id).FirstAsync(token); }
    private void Audit(BrassLedgerDbContext db, Guid companyId, string action, Guid id, object detail) => db.BusinessAuditEntries.Add(new() { Id = Guid.NewGuid(), CompanyId = companyId, UserId = ResolveUserId(), Action = action, EntityType = nameof(PayrollSsaOriginalWageFile), EntityId = id, DetailJson = JsonSerializer.Serialize(detail), OccurredAtUtc = DateTimeOffset.UtcNow });
}
