using System.Text.Json;

namespace BrassLedger.Application.Accounting;

public interface IConsolidationService
{
    Task<TransactionResult> SaveExchangeRateAsync(SaveExchangeRateRequest request, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<ExchangeRateSnapshot>> GetExchangeRatesAsync(CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveGroupAsync(SaveConsolidationGroupRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveOwnershipPeriodAsync(SaveConsolidationOwnershipPeriodRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveAccountMappingAsync(SaveConsolidationAccountMappingRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveTradingPartnerAsync(SaveConsolidationTradingPartnerRequest request, CancellationToken cancellationToken = default);
    Task<ConsolidationTradingPartnerWorkspace?> GetTradingPartnerWorkspaceAsync(Guid groupId, CancellationToken cancellationToken = default);
    Task<ConsolidationIntercompanyDiscoveryResult> DiscoverIntercompanyMatchesAsync(DiscoverConsolidationIntercompanyMatchesRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> SetIntercompanyMatchDecisionAsync(SetConsolidationIntercompanyMatchDecisionRequest request, CancellationToken cancellationToken = default);
    Task<ConsolidationIntercompanyMatchWorkspace?> GetIntercompanyMatchWorkspaceAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<IReadOnlyList<ConsolidationGroupSnapshot>> GetGroupsAsync(CancellationToken cancellationToken = default);
    Task<ConsolidationAccountMappingWorkspace?> GetAccountMappingWorkspaceAsync(Guid groupId, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveStatementPresentationAsync(SaveConsolidationStatementPresentationRequest request, CancellationToken cancellationToken = default);
    Task<ConsolidationStatementPresentationWorkspace?> GetStatementPresentationWorkspaceAsync(Guid groupId, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveDisclosurePackageAsync(SaveConsolidationDisclosurePackageRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> ApproveDisclosurePackageAsync(ConsolidationDisclosureActionRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> RejectDisclosurePackageAsync(ConsolidationDisclosureDecisionRequest request, CancellationToken cancellationToken = default);
    Task<ConsolidationDisclosureWorkspace?> GetDisclosureWorkspaceAsync(Guid groupId, CancellationToken cancellationToken = default);
    Task<TransactionResult> SaveAdjustmentAsync(SaveConsolidationAdjustmentRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> ApproveAdjustmentAsync(ConsolidationAdjustmentActionRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> RejectAdjustmentAsync(ConsolidationAdjustmentDecisionRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> PostAdjustmentAsync(ConsolidationAdjustmentActionRequest request, CancellationToken cancellationToken = default);
    Task<TransactionResult> ReverseAdjustmentAsync(ReverseConsolidationAdjustmentRequest request, CancellationToken cancellationToken = default);
    Task<ConsolidationAdjustmentWorkspace?> GetAdjustmentWorkspaceAsync(Guid groupId, CancellationToken cancellationToken = default);
    Task<ConsolidatedBalanceReport?> GetBalanceReportAsync(Guid groupId, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<ConsolidatedBalanceReport?> GetBalanceReportAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<ConsolidatedStatementPackage?> GetStatementPackageAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<string?> ExportStatementPackageCsvAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<byte[]?> ExportStatementPackageExcelAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<byte[]?> ExportStatementPackagePdfAsync(Guid groupId, DateOnly periodStart, DateOnly asOf, CancellationToken cancellationToken = default);
    Task<ConsolidatedComparativeStatementPackage?> GetComparativeStatementPackageAsync(Guid groupId, DateOnly currentPeriodStart, DateOnly currentAsOf, DateOnly comparisonPeriodStart, DateOnly comparisonAsOf, CancellationToken cancellationToken = default);
    Task<string?> ExportComparativeStatementPackageCsvAsync(Guid groupId, DateOnly currentPeriodStart, DateOnly currentAsOf, DateOnly comparisonPeriodStart, DateOnly comparisonAsOf, CancellationToken cancellationToken = default);
    Task<byte[]?> ExportComparativeStatementPackageExcelAsync(Guid groupId, DateOnly currentPeriodStart, DateOnly currentAsOf, DateOnly comparisonPeriodStart, DateOnly comparisonAsOf, CancellationToken cancellationToken = default);
    Task<byte[]?> ExportComparativeStatementPackagePdfAsync(Guid groupId, DateOnly currentPeriodStart, DateOnly currentAsOf, DateOnly comparisonPeriodStart, DateOnly comparisonAsOf, CancellationToken cancellationToken = default);
}

public sealed record SaveExchangeRateRequest(string BaseCurrency, string QuoteCurrency, decimal Rate, DateOnly EffectiveOn, string Source, Guid? Id = null, string RateType = "Closing", DateOnly? PeriodStartOn = null, string SourceReference = "", DateOnly? RetrievedOn = null, bool IsActive = true, string ConcurrencyToken = "");
public sealed record ExchangeRateSnapshot(Guid Id, string BaseCurrency, string QuoteCurrency, decimal Rate, string RateType, DateOnly? PeriodStartOn, DateOnly EffectiveOn, string Source, string SourceReference, DateOnly? RetrievedOn, bool IsActive, string ConcurrencyToken);
public sealed record ConsolidationMemberRequest(Guid CompanyId, decimal OwnershipPercentage = 1m, DateOnly? EffectiveFrom = null, DateOnly? EffectiveThrough = null, string ConsolidationBasis = "ProportionateInterest", string BasisRationale = "", DateOnly? BasisReviewedOn = null);
public sealed record SaveConsolidationGroupRequest(Guid? Id, string Name, string ReportingCurrency, IReadOnlyList<ConsolidationMemberRequest> Members, bool IsActive = true, string ConcurrencyToken = "", string CtaAccountNumber = "", string CtaAccountName = "", string NciAccountNumber = "", string NciAccountName = "");
public sealed record SaveConsolidationOwnershipPeriodRequest(Guid? Id, Guid ConsolidationGroupId, Guid MemberCompanyId, decimal OwnershipPercentage, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, string ConcurrencyToken = "", string ConsolidationBasis = "ProportionateInterest", string BasisRationale = "", DateOnly? BasisReviewedOn = null);
public sealed record ConsolidationGroupSnapshot(Guid Id, string Name, string ReportingCurrency, bool IsActive, string ConcurrencyToken, IReadOnlyList<ConsolidationGroupMemberSnapshot> Members, string CtaAccountNumber, string CtaAccountName, string NciAccountNumber = "", string NciAccountName = "");
public sealed record ConsolidationGroupMemberSnapshot(Guid Id, Guid CompanyId, string CompanyName, string BaseCurrency, decimal OwnershipPercentage, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, string ConcurrencyToken, string ConsolidationBasis = "ProportionateInterest", string BasisRationale = "", DateOnly? BasisReviewedOn = null);
public sealed record SaveConsolidationAccountMappingRequest(Guid? Id, Guid ConsolidationGroupId, Guid MemberCompanyId, Guid MemberAccountId, string ReportingAccountNumber, string ReportingAccountName, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive = true, string ConcurrencyToken = "", string? TranslationMethod = null, string CashFlowActivity = "Unclassified", string CashFlowRationale = "", DateOnly? CashFlowReviewedOn = null);
public sealed record ConsolidationSourceAccountSnapshot(Guid CompanyId, string CompanyName, Guid AccountId, string AccountNumber, string AccountName, string AccountType);
public sealed record ConsolidationAccountMappingSnapshot(Guid Id, Guid CompanyId, string CompanyName, Guid AccountId, string AccountNumber, string AccountName, string AccountType, string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType, string TranslationMethod, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive, string ConcurrencyToken, string CashFlowActivity = "Unclassified", string CashFlowRationale = "", DateOnly? CashFlowReviewedOn = null);
public sealed record ConsolidationAccountMappingWorkspace(Guid GroupId, string GroupName, IReadOnlyList<ConsolidationSourceAccountSnapshot> SourceAccounts, IReadOnlyList<ConsolidationAccountMappingSnapshot> Mappings);
public sealed record SaveConsolidationStatementPresentationRequest(Guid? Id, Guid ConsolidationGroupId, string StatementCode, string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType, string SectionCode, string SectionName, int SectionSortOrder, string LineCaption, int LineSortOrder, string Rationale, DateOnly ReviewedOn, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive = true, string ConcurrencyToken = "");
public sealed record ConsolidationStatementPresentationCandidate(string StatementCode, string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType);
public sealed record ConsolidationStatementPresentationSnapshot(Guid Id, string StatementCode, string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType, string SectionCode, string SectionName, int SectionSortOrder, string LineCaption, int LineSortOrder, string Rationale, DateOnly ReviewedOn, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive, string ConcurrencyToken);
public sealed record ConsolidationStatementPresentationWorkspace(Guid GroupId, string GroupName, IReadOnlyList<ConsolidationStatementPresentationCandidate> Candidates, IReadOnlyList<ConsolidationStatementPresentationSnapshot> Presentations);
public sealed record FinancingLiabilityDisclosureRow(string LiabilityCode, string LiabilityName, string BalanceSheetLine, decimal OpeningBalance, decimal FinancingCashFlows, decimal Acquisitions, decimal Disposals, decimal ForeignExchangeChanges, decimal FairValueChanges, decimal OtherNonCashChanges, decimal ClosingBalance, string OtherNonCashExplanation, string SourceReference,
    Dictionary<string, JsonElement>? Extensions = null);
public sealed record SupplierFinanceDisclosureRow(string ArrangementCode, string ArrangementName, string KeyTerms, string BalanceSheetLine, decimal OpeningOutstanding, decimal ObligationsConfirmed, decimal ObligationsPaid, decimal ClosingOutstanding, decimal SuppliersAlreadyPaid, int? PaymentDueMinimumDays, int? PaymentDueMaximumDays, int? ComparablePayablesDueMinimumDays, int? ComparablePayablesDueMaximumDays, string SecurityOrGuarantees, string LiquidityRiskNotes, string SourceReference,
    Dictionary<string, JsonElement>? Extensions = null);
public sealed record ConsolidationNarrativeDisclosure(string Category, string Code, string Title, int SortOrder, string Narrative, string SourceReference,
    Dictionary<string, JsonElement>? Extensions = null);
public sealed record ConsolidationDisclosureDocument(int SchemaVersion, IReadOnlyList<FinancingLiabilityDisclosureRow> FinancingLiabilities, IReadOnlyList<SupplierFinanceDisclosureRow> SupplierFinanceArrangements, IReadOnlyList<ConsolidationNarrativeDisclosure> NarrativeDisclosures,
    Dictionary<string, JsonElement>? Extensions = null);
public sealed record SaveConsolidationDisclosurePackageRequest(Guid? Id, Guid ConsolidationGroupId, DateOnly PeriodStart, DateOnly AsOf, string FrameworkCode, string FrameworkEdition, ConsolidationDisclosureDocument Content, string ReviewNotes = "", string ConcurrencyToken = "");
public sealed record ConsolidationDisclosureActionRequest(Guid ConsolidationGroupId, Guid DisclosurePackageId, string ConcurrencyToken);
public sealed record ConsolidationDisclosureDecisionRequest(Guid ConsolidationGroupId, Guid DisclosurePackageId, string Reason, string ConcurrencyToken);
public sealed record ConsolidationDisclosurePackageSnapshot(Guid Id, DateOnly PeriodStart, DateOnly AsOf, string FrameworkCode, string FrameworkEdition, int SchemaVersion, string ContentSha256, ConsolidationDisclosureDocument Content, string Status, string PreparedBy, DateTimeOffset PreparedAtUtc, string? ApprovedBy, DateTimeOffset? ApprovedAtUtc, string? RejectedBy, DateTimeOffset? RejectedAtUtc, string DecisionReason, string ReviewNotes, string ConcurrencyToken);
public sealed record ConsolidationDisclosureWorkspace(Guid GroupId, string GroupName, string ReportingCurrency, IReadOnlyList<ConsolidationDisclosurePackageSnapshot> Packages);
public sealed record SaveConsolidationTradingPartnerRequest(Guid? Id, Guid ConsolidationGroupId, Guid MemberCompanyId, Guid CounterpartyCompanyId, Guid? CustomerId, Guid? VendorId, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive = true, string ConcurrencyToken = "");
public sealed record ConsolidationTradingPartnerCandidateSnapshot(Guid CompanyId, string CompanyName, string Kind, Guid CounterpartyRecordId, string Number, string Name);
public sealed record ConsolidationTradingPartnerSnapshot(Guid Id, Guid MemberCompanyId, string MemberCompanyName, Guid CounterpartyCompanyId, string CounterpartyCompanyName, string Kind, Guid CounterpartyRecordId, string Number, string Name, DateOnly EffectiveFrom, DateOnly? EffectiveThrough, bool IsActive, string ConcurrencyToken);
public sealed record ConsolidationTradingPartnerWorkspace(Guid GroupId, string GroupName, IReadOnlyList<ConsolidationGroupMemberSnapshot> Members, IReadOnlyList<ConsolidationTradingPartnerCandidateSnapshot> Candidates, IReadOnlyList<ConsolidationTradingPartnerSnapshot> Links);
public sealed record DiscoverConsolidationIntercompanyMatchesRequest(Guid ConsolidationGroupId, DateOnly PeriodStart, DateOnly AsOf);
public sealed record ConsolidationIntercompanyDiscoveryResult(bool Succeeded, string ErrorMessage, int CreatedCount, int RefreshedCount, IReadOnlyList<string> Warnings);
public sealed record SetConsolidationIntercompanyMatchDecisionRequest(Guid ConsolidationGroupId, Guid MatchId, string Decision, string Reason, string ConcurrencyToken);
public sealed record ConsolidationIntercompanyMatchSnapshot(Guid Id, Guid SellerCompanyId, string SellerCompanyName, Guid BuyerCompanyId, string BuyerCompanyName, Guid SalesInvoiceId, string InvoiceNumber, DateOnly InvoiceDate, Guid VendorBillId, string BillNumber, DateOnly BillDate, string MatchReference, string Currency, decimal Amount, decimal SellerBalanceDue, decimal BuyerBalanceDue, string Status, string ReviewReason, string? ReviewedBy, DateTimeOffset? ReviewedAtUtc, Guid? ConsolidationAdjustmentBatchId, string ConcurrencyToken);
public sealed record ConsolidationIntercompanyMatchWorkspace(Guid GroupId, string GroupName, DateOnly PeriodStart, DateOnly AsOf, IReadOnlyList<ConsolidationIntercompanyMatchSnapshot> Matches);
public sealed record ConsolidationAdjustmentLineRequest(string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType, decimal Debit, decimal Credit, string Description = "", Guid? SourceCompanyId = null, Guid? CounterpartyCompanyId = null);
public sealed record SaveConsolidationAdjustmentRequest(Guid? Id, Guid ConsolidationGroupId, DateOnly PeriodStart, DateOnly AsOf, string Kind, string Reference, string Description, string MatchReference, IReadOnlyList<ConsolidationAdjustmentLineRequest> Lines, string ConcurrencyToken = "", Guid? SubjectCompanyId = null);
public sealed record ConsolidationAdjustmentActionRequest(Guid ConsolidationGroupId, Guid AdjustmentBatchId, string ConcurrencyToken);
public sealed record ConsolidationAdjustmentDecisionRequest(Guid ConsolidationGroupId, Guid AdjustmentBatchId, string Reason, string ConcurrencyToken);
public sealed record ReverseConsolidationAdjustmentRequest(Guid ConsolidationGroupId, Guid AdjustmentBatchId, string Reason, string ConcurrencyToken);
public sealed record ConsolidationReportingAccountSnapshot(string AccountNumber, string AccountName, string AccountType);
public sealed record ConsolidationAdjustmentLineSnapshot(Guid Id, int Sequence, string ReportingAccountNumber, string ReportingAccountName, string ReportingAccountType, decimal Debit, decimal Credit, string Description, Guid? SourceCompanyId, string? SourceCompanyName, Guid? CounterpartyCompanyId, string? CounterpartyCompanyName);
public sealed record ConsolidationAdjustmentSnapshot(Guid Id, DateOnly PeriodStart, DateOnly AsOf, string Kind, string Reference, string Description, string MatchReference, string Status, string PreparedBy, DateTimeOffset PreparedAtUtc, string? ApprovedBy, DateTimeOffset? ApprovedAtUtc, string? RejectedBy, DateTimeOffset? RejectedAtUtc, string? PostedBy, DateTimeOffset? PostedAtUtc, string DecisionReason, Guid? ReversalOfBatchId, Guid? ReversedByBatchId, string ReversalReason, string ConcurrencyToken, IReadOnlyList<ConsolidationAdjustmentLineSnapshot> Lines, Guid? SubjectCompanyId = null, string? SubjectCompanyName = null);
public sealed record ConsolidationAdjustmentWorkspace(Guid GroupId, string GroupName, string ReportingCurrency, IReadOnlyList<ConsolidationReportingAccountSnapshot> ReportingAccounts, IReadOnlyList<ConsolidationGroupMemberSnapshot> Members, IReadOnlyList<ConsolidationAdjustmentSnapshot> Adjustments);
public sealed record ConsolidatedBalanceReport(Guid GroupId, string GroupName, string ReportingCurrency, DateOnly PeriodStart, DateOnly AsOf, IReadOnlyList<ConsolidatedAccountBalance> Accounts, IReadOnlyList<string> Warnings, decimal TranslationAdjustment);
public sealed record ConsolidatedAccountContribution(Guid? CompanyId, string CompanyName, string SourceAccountNumber, string SourceAccountName, string SourceKind, string Reference, decimal ConvertedBalance, string TranslationMethod);
public sealed record ConsolidatedAccountBalance(string AccountNumber, string AccountName, string AccountType, decimal ConvertedBalance, string TranslationMethod = "", IReadOnlyList<ConsolidatedAccountContribution>? Contributions = null);
public sealed record ConsolidatedStatementAccount(string AccountNumber, string AccountName, string AccountType, decimal Amount, IReadOnlyList<ConsolidatedAccountContribution> Contributions);
public sealed record ConsolidatedStatementSection(string Code, string Name, IReadOnlyList<ConsolidatedStatementAccount> Accounts, decimal Total);
public sealed record ConsolidatedFinancialStatement(string Code, string Name, IReadOnlyList<ConsolidatedStatementSection> Sections, decimal Total, decimal ReconciliationDifference);
public sealed record ConsolidatedStatementReconciliation(decimal Assets, decimal Liabilities, decimal RecordedEquity, decimal NetIncome, decimal LiabilitiesAndEquity, decimal BalanceSheetDifference, decimal OpeningEquity, decimal DirectEquityMovement, decimal PresentedEndingEquity, decimal EquityStatementDifference, decimal OpeningCash, decimal EndingCash, decimal NetCashChange, decimal PresentedCashChange, decimal CashFlowDifference);
public sealed record ConsolidatedStatementPackage(Guid GroupId, string GroupName, string ReportingCurrency, DateOnly PeriodStart, DateOnly AsOf, ConsolidatedFinancialStatement BalanceSheet, ConsolidatedFinancialStatement IncomeStatement, ConsolidatedFinancialStatement EquityStatement, ConsolidatedFinancialStatement CashFlowStatement, ConsolidatedStatementReconciliation Reconciliation, IReadOnlyList<string> Warnings, bool IsComplete, IReadOnlyList<ConsolidationDisclosurePackageSnapshot>? DisclosurePackages = null);
public sealed record ConsolidatedComparativeStatementLine(string AccountNumber, string AccountType, string CurrentSectionCode, string CurrentSectionName, string CurrentLineCaption, decimal CurrentAmount, string ComparisonSectionCode, string ComparisonSectionName, string ComparisonLineCaption, decimal ComparisonAmount, decimal Variance);
public sealed record ConsolidatedComparativeFinancialStatement(string Code, string Name, decimal CurrentTotal, decimal ComparisonTotal, decimal Variance, IReadOnlyList<ConsolidatedComparativeStatementLine> Lines);
public sealed record ConsolidatedComparativeStatementPackage(Guid GroupId, string GroupName, string ReportingCurrency, ConsolidatedStatementPackage Current, ConsolidatedStatementPackage Comparison, IReadOnlyList<ConsolidatedComparativeFinancialStatement> Statements, IReadOnlyList<string> Warnings, bool IsComplete);
